name: CI
on: push
jobs:
  lint:
    name: Lint and test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.x"
      - run: |
          deno lint --unstable ./test ./src
          deno test --import-map=import_map.json --unstable ./test
